apiVersion: apps/v1
kind: Deployment
metadata:
  name: taotao-cloud-gateway
  namespace: dev
  labels:
    app: taotao-cloud-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taotao-cloud-gateway
  template:
    metadata:
      labels:
        app: taotao-cloud-gateway
    spec:
      containers:
        - name: taotao-cloud-gateway
          image: 192.168.99.240:8443/taotao-cloud/taotao-cloud-gateway:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          ports:
            - name: gateway-port
              containerPort: 9900
---
apiVersion: v1
kind: Service
metadata:
  name: taotao-cloud-gateway-service
  namespace: dev
  labels:
    app: taotao-cloud-gateway-service
spec:
  type: NodePort
  selector:
    app: taotao-cloud-gateway
  ports:
    - name: gateway-service-port
      protocol: TCP
      port: 9900
      targetPort: 9900
      nodePort: 30000
