server:
  port: 9700
  http2:
    enabled: true
  undertow:
    buffer-size: 2048
    direct-buffers: true

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: taotao-cloud-uc-center
