apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: taotao-cloud-pay-biz
  namespace: taotao-cloud-prod
  labels:
    app: taotao-cloud-pay-biz
    version: 1.0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-taotao-cloud-pay-biz
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-taotao-cloud-pay-biz
        app: taotao-cloud-pay-biz
    spec:
      containers:
        - name: taotao-cloud-pay-biz
          image: 172.16.10.230:88/taotao-cloud/taotao-cloud-pay-biz:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 9800
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 2
            spaycessThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 9800
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 2
            spaycessThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 2
              memory: 2048Mi
            limits:
              cpu: 2
              memory: 2048Mi
          env:
            - name: LOCAL_KEY
              value: value
            - name: CONFIG_MAP_KEY
              valueFrom:
                configMapKeyRef:
                  name: special-config
                  key: special.type
          ports:
            - name: http
              containerPort: 9700
          volumeMounts:
            - name: log-cache
              mount: /tmp/log
            - name: sdb
              mountPath: /data/media
            - name: taotao-cloud-pay-biz-nfs-client
              mountPath: /mnt/nfs
            - name: taotao-cloud-pay-biz-volume-config
              mountPath: /etc/config
            - name: rbd-pvc
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: ali
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  volumes:
    - name: log-cache
      emptyDir: {}
    - name: sdb
      hostPath:
        path: /opt/taotao/cloud/pay/data
    - name: taotao-cloud-auth-volume-config
      configMap:
        name: taotao-cloud-pay-biz-volume-config
        items:
          - key: log-script
            path: path/to/log-script
    - name: taotao-cloud-pay-biz-nfs-client
      nfs:
        server: 10.42.0.55
        path: /opt/public
    - name: rbd-pvc
      persistentVolumeClaim:
        claimName: rbd-pvc1

---

apiVersion: v1
kind: Service
matadata:
  name: taotao-cloud-pay-biz-service
  namespace: taotao-cloud-prod
  labels:
    app: taotao-cloud-pay-biz-service
    version: 1.0
    kubernetes.io/cluster-service: "true"
  annotations:
    app: taotao-cloud-pay-biz-service
spec:
  selector:
    app: taotao-cloud-pay-biz
  ports:
    - name: taotao-cloud-pay-biz-service-port
      protocol: TCP
      port: 9800
      targetPort: 9800
      nodePort: 9800
